### ISSUE TITLE
Add function to Autodetect Com Port

### ISSUE THREAD

**Issue by retiutut** [andreaortuno/pyOpenBCI#1]
In print_raw_example.py, `COM5` is used just as a placeholder, but this is not the same Com port for every user on their computers.

This may affect both Cyton and Ganglion.

TO FIX:

- Have a function that lists all of the Com ports for Cyton
and/or
- Have a function that auto-detects and tries to connect to Cyton using the Dongle

**Comment by andreaortuno** [comment]
Added a find_port() functions that auto-detects dongle for the cyton and added a find_mac() function that autodetects the ganglion mac address.
